### ISSUE TITLE
ls: no se puede acceder a '*.ovpn': No existe el archivo o el directorio

### ISSUE THREAD

**Issue by doomedraven** [Hackplayers/4nonimizer#12]
`ls: no se puede acceder a '*.ovpn': No existe el archivo o el directorio`

pasa despues de instalar desde git y actualizar lista de ovpns en ubuntu 16.04

<img width="785" alt="captura de pantalla 2017-02-22 a las 23 19 14" src="https://cloud.githubusercontent.com/assets/1856495/23235335/6d1a6b9e-f955-11e6-83f5-2af692668f29.png">

**Comment by Hackplayers** [comment]
Los ficheros .ovpn de 7proxies son ofrecidos por el proveedor para 4nonimizer y deben descargarse desde el mismo repositorio: https://github.com/Hackplayers/4nonimizer/tree/master/vpn/7proxies.
Clona de nuevo el repositorio o descargalos manualmente.

Saludos y gracias por el reporte.
