### ISSUE TITLE
How to install it on antergos or arch linux?

### ISSUE THREAD

**Issue by zief** [Hackplayers/4nonimizer#15]
./4nonimizer: line 178: lsb_release: command not found
./4nonimizer: line 178: [: =: unary operator expected
./4nonimizer: line 178: lsb_release: command not found
./4nonimizer: line 178: [: =: unary operator expected
./4nonimizer: line 178: lsb_release: command not found
./4nonimizer: line 178: [: =: unary operator expected
./4nonimizer: line 178: lsb_release: command not found
./4nonimizer: line 178: [: =: unary operator expected
./4nonimizer: line 178: lsb_release: command not found
./4nonimizer: line 178: [: =: unary operator expected
./4nonimizer: line 178: lsb_release: command not found
./4nonimizer: line 178: [: =: unary operator expected
./4nonimizer: line 178: lsb_release: command not found
./4nonimizer: line 178: [: =: unary operator expected
./4nonimizer: line 183: lsb_release: command not found
./4nonimizer: line 183: [: =: unary operator expected
./4nonimizer: line 183: lsb_release: command not found
./4nonimizer: line 183: [: =: unary operator expected

[*] Your distro is not supported

:D i hope i can install it on my antergos.

**Comment by vmotos** [comment]
I've just added the "antergos support". Thanks you so much for the feedback in that distro.

**Comment by zief** [comment]
I think lsb_release is not by default in antergos
you must install it from community or official using 

yaourt -S lsb-release or sudo pacman -S lsb-release

thanks
