### ISSUE TITLE
Add bash & zsh auto completion

### ISSUE THREAD

**Issue by Armanmd** [Hackplayers/4nonimizer#24]
_**For a perfect cli tool. We need bash & zsh auto-completion.so i think it shouldn't be super hard to do the same for 4nonimizer.try to do that as soon as possible**_

**Comment by Armanmd** [comment]
**_i find easy bash completion tutorial?(please check it)_**

[one](https://unix.stackexchange.com/questions/4738/an-easy-bash-completion-tutorial)

[two](https://debian-administration.org/article/316/An_introduction_to_bash_completion_part_1)

**Comment by vmotos** [comment]
Follow instructions in function autocom ()
