### ISSUE TITLE
4nonimizer - Logout/Signout

### ISSUE THREAD

**Issue by 4n0n1m1z3r** [Hackplayers/4nonimizer#26]
Hi,

when I'm starting the 4nonimizer over the terminal with:
cmd> 4nonimizer start

it logs me out. When it tries to connect with a VPN it instantly kicks me off and i've to relog. I can't find a solution to this. I never had this kind of issue but I recently updated my OS to Kali Linux 2017.2 and that's when the issue started. After the relog I've to restart the Network-manager because it goes down.

Greets.

**Comment by vmotos** [comment]
Could be a problem with the unit service anon.service?
Please, try '4nonimizer disableboot' and give us the feedback. We will also try to reproduce problem updating Kali...

**Comment by padawan155** [comment]
I also confirm that this happens. I was able to uninstall it, but it kicked me out too. Kali 2.0. I had to roll back my virtualbox to fix.

**Comment by vmotos** [comment]
I have not been able to reproduce the problem yet. It could be a problem with the service or with openvpn. Could you give us more information like the boot logs?

**Comment by vmotos** [comment]
No answer.
