### ISSUE TITLE
There is a problem starting openvpn. Please, check nohup.out for details  (in using 4nonimizer)

### ISSUE THREAD

**Issue by destroyeramit** [Hackplayers/4nonimizer#27]
[+] There is a problem starting openvpn. Please, check nohup.out for details

Thu Oct 26 10:12:27 2017 WARNING: file 'pass.txt' is group or others accessible
Thu Oct 26 10:12:27 2017 OpenVPN 2.4.3 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jun 30 2017
Thu Oct 26 10:12:27 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Thu Oct 26 10:12:27 2017 Error reading username from Auth authfile: pass.txt
Thu Oct 26 10:12:27 2017 Exiting due to fatal error
Thu Oct 26 23:20:58 2017 WARNING: file 'pass.txt' is group or others accessible
Thu Oct 26 23:20:58 2017 OpenVPN 2.4.3 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jun 30 2017
Thu Oct 26 23:20:58 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Thu Oct 26 23:20:58 2017 Error reading username from Auth authfile: pass.txt
Thu Oct 26 23:20:58 2017 Exiting due to fatal error
Fri Oct 27 14:20:18 2017 WARNING: file 'pass.txt' is group or others accessible
Fri Oct 27 14:20:18 2017 OpenVPN 2.4.3 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jun 30 2017
Fri Oct 27 14:20:18 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Fri Oct 27 14:20:18 2017 Error reading username from Auth authfile: pass.txt
Fri Oct 27 14:20:18 2017 Exiting due to fatal error
Fri Oct 27 14:26:14 2017 WARNING: file 'pass.txt' is group or others accessible
Fri Oct 27 14:26:14 2017 OpenVPN 2.4.3 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jun 30 2017
Fri Oct 27 14:26:14 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Fri Oct 27 14:26:14 2017 Error reading username from Auth authfile: pass.txt
Fri Oct 27 14:26:14 2017 Exiting due to fatal error
Fri Oct 27 14:41:27 2017 WARNING: file 'pass.txt' is group or others accessible
Fri Oct 27 14:41:27 2017 OpenVPN 2.4.3 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jun 30 2017
Fri Oct 27 14:41:27 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Fri Oct 27 14:41:27 2017 Error reading username from Auth authfile: pass.txt
Fri Oct 27 14:41:27 2017 Exiting due to fatal error
Fri Oct 27 14:57:37 2017 WARNING: file 'pass.txt' is group or others accessible
Fri Oct 27 14:57:37 2017 OpenVPN 2.4.3 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jun 30 2017
Fri Oct 27 14:57:37 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Fri Oct 27 14:57:37 2017 Error reading username from Auth authfile: pass.txt
Fri Oct 27 14:57:37 2017 Exiting due to fatal error

**Comment by brubrant** [comment]
Did you fill pass.txt with your credentials?

**Comment by vmotos** [comment]
Please fill pass.txt with your credentials

**Comment by destroyeramit** [comment]
Thank you

**Comment by aman-17** [comment]
> Did you fill pass.txt with your credentials?
Hello, I'm new to this.
which credentials do we need to add?
