### ISSUE TITLE
VPN Book as default?

### ISSUE THREAD

**Issue by PacketSmuggler** [Hackplayers/4nonimizer#3]
How did VPN Book end up as default when you could be using Cryptostorm?

Cryptostorm's free service is capped at 256k, but it's completely free.

https://github.com/cryptostorm/cryptostorm_client_configuration_files/tree/master/cryptofree

Paid Cryptostorm customers would be using the first Zero Customer Knowledge VPN. Show up in IRC, buy a token (proof of purchase) with Bitcoin, and there isn't any way you're being logged - Cryptostorm simply makes it a point to never collect enough information to do that in the first place.

Free is free, if developers shoot me a PM I can arrange for some free tokens so you guys can test the rest of the service, too.

**Comment by vmotos** [comment]
256k is very low speed  to use a default VPN. Should be free but also faster.

However, we're going to add Cryptostorm to our list of VPNs, first in the devel branch.

**Comment by charly837** [comment]
Close this issue 

Thanks for the comment
