### ISSUE TITLE
Can't connect no any VPN services after command "4nonimizer update_vpns"

### ISSUE THREAD

**Issue by shuhrat02** [Hackplayers/4nonimizer#32]
hello guys!
After command `4nonimizer update_vpns` does not work any VPN service.
for example, this is a log of the issue:

`[+] There is a problem starting openvpn. Please, check nohup.out for details

Sun Jan 28 16:48:55 2018 OPTIONS IMPORT: --ifconfig/up options modified
Sun Jan 28 16:48:55 2018 OPTIONS IMPORT: route options modified
Sun Jan 28 16:48:55 2018 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Sun Jan 28 16:48:55 2018 OPTIONS IMPORT: peer-id set
Sun Jan 28 16:48:55 2018 OPTIONS IMPORT: adjusting link_mtu to 1627
Sun Jan 28 16:48:55 2018 OPTIONS IMPORT: data channel crypto options modified
Sun Jan 28 16:48:55 2018 Data Channel: using negotiated cipher 'AES-256-GCM'
Sun Jan 28 16:48:55 2018 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Jan 28 16:48:55 2018 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Jan 28 16:48:55 2018 ROUTE_GATEWAY 192.168.88.1/255.255.255.0 IFACE=wlan0 HWADDR=e0:00:a5:00:1c:f7
Sun Jan 28 16:48:55 2018 TUN/TAP device tun3 opened
Sun Jan 28 16:48:55 2018 TUN/TAP TX queue length set to 100
Sun Jan 28 16:48:55 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Sun Jan 28 16:48:55 2018 /sbin/ip link set dev tun3 up mtu 1500
Sun Jan 28 16:48:55 2018 /sbin/ip addr add dev tun3 local 10.12.0.214 peer 10.12.0.213
Sun Jan 28 16:48:57 2018 /sbin/ip route add 178.65.193.233/32 via 192.168.88.1
Sun Jan 28 16:48:57 2018 /sbin/ip route add 0.0.0.0/1 via 10.12.0.213
Sun Jan 28 16:48:57 2018 /sbin/ip route add 128.0.0.0/1 via 10.12.0.213
Sun Jan 28 16:48:57 2018 /sbin/ip route add 10.12.0.1/32 via 10.12.0.213
Sun Jan 28 16:48:57 2018 Initialization Sequence Completed
Thu Feb  1 22:03:09 2018 WARNING: file 'pass.txt' is group or others accessible
Thu Feb  1 22:03:09 2018 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Dec 10 2017
Thu Feb  1 22:03:09 2018 library versions: OpenSSL 1.1.0g  2 Nov 2017, LZO 2.08
Thu Feb  1 22:03:10 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]198.186.193.94:443
Thu Feb  1 22:03:10 2018 UDP link local: (not bound)
Thu Feb  1 22:03:10 2018 UDP link remote: [AF_INET]198.186.193.94:443
Thu Feb  1 22:03:10 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Feb  1 22:03:13 2018 [VPN] Peer Connection Initiated with [AF_INET]198.186.193.94:443
Thu Feb  1 22:03:14 2018 AUTH: Received control message: AUTH_FAILED
Thu Feb  1 22:03:14 2018 SIGTERM[soft,auth-failure] received, process exiting
`

**Comment by vmotos** [comment]
The problem is 'AUTH_FAILED'.. please tell me which provide you are using and check the file pass.txt.

**Comment by shuhrat02** [comment]
doesnot work any listed provider, even with (auto-login) options

**Comment by vmotos** [comment]
Could you tell me the provider with auto-login which fails?

Regards,

**Comment by shuhrat02** [comment]
All of them... for example VPNbook, VPNgate

**Comment by vmotos** [comment]
For instance, execute /opt/4nonimizer/vpn/vpnbook/vpn-get-pass.sh and check if pass.txt is filled with corresponding credentials (or paste here any error).

**Comment by damienrobins** [comment]
Same issues here

**Comment by Hackplayers** [comment]
Please, execute  /opt/4nonimizer/vpn/vpnbook/vpn-get-pass.sh and check if pass.txt is filled with corresponding credentials (or paste here any error).

**Comment by vmotos** [comment]
Closed (no answer).

**Comment by desmond436** [comment]
pass.txt file is black not what?
