### ISSUE TITLE
Unable to connect 

### ISSUE THREAD

**Issue by suryansh55** [Hackplayers/4nonimizer#34]
Everytime I start 4nonimizer it says There is a problem starting openvpn . When I first installed it , it was working fine but now it's  giving problem even my anonsurf surf is not working now . I'm using ParrotSec OS . Please Help

**Comment by vmotos** [comment]
Could you paste the complete openvpn log, please?

**Comment by suryansh55** [comment]
[+] There is a problem starting openvpn. Please, check nohup.out for details

Fri Mar  2 16:24:08 2018 WARNING: file 'pass.txt' is group or others accessible
Fri Mar  2 16:24:08 2018 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Dec 10 2017
Fri Mar  2 16:24:08 2018 library versions: OpenSSL 1.1.0g  2 Nov 2017, LZO 2.08
Fri Mar  2 16:24:08 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Fri Mar  2 16:24:08 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]198.7.62.204:53
Fri Mar  2 16:24:08 2018 Socket Buffers: R=[212992->212992] S=[212992->212992]
Fri Mar  2 16:24:08 2018 UDP link local: (not bound)
Fri Mar  2 16:24:08 2018 UDP link remote: [AF_INET]198.7.62.204:53
Fri Mar  2 16:24:08 2018 TLS: Initial packet from [AF_INET]198.7.62.204:53, sid=e2750a10 0c5ce314
Fri Mar  2 16:24:08 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri Mar  2 16:24:09 2018 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Fri Mar  2 16:24:09 2018 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Fri Mar  2 16:24:11 2018 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 1024 bit RSA
Fri Mar  2 16:24:11 2018 [vpnbook.com] Peer Connection Initiated with [AF_INET]198.7.62.204:53
Fri Mar  2 16:24:13 2018 SENT CONTROL [vpnbook.com]: 'PUSH_REQUEST' (status=1)
Fri Mar  2 16:24:13 2018 AUTH: Received control message: AUTH_FAILED
Fri Mar  2 16:24:13 2018 SIGTERM[soft,auth-failure] received, process exiting
Fri Mar  2 16:32:16 2018 WARNING: file 'pass.txt' is group or others accessible
Fri Mar  2 16:32:16 2018 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Dec 10 2017
Fri Mar  2 16:32:16 2018 library versions: OpenSSL 1.1.0g  2 Nov 2017, LZO 2.08
Fri Mar  2 16:32:57 2018 ERROR: Failed retrieving username or password
Fri Mar  2 16:32:57 2018 Exiting due to fatal error
Fri Mar  2 16:34:20 2018 WARNING: file 'pass.txt' is group or others accessible
Fri Mar  2 16:34:20 2018 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Dec 10 2017
Fri Mar  2 16:34:20 2018 library versions: OpenSSL 1.1.0g  2 Nov 2017, LZO 2.08
Fri Mar  2 16:35:50 2018 ERROR: Failed retrieving username or password
Fri Mar  2 16:35:50 2018 Exiting due to fatal error
Mon Mar  5 16:43:16 2018 WARNING: file 'pass.txt' is group or others accessible
Mon Mar  5 16:43:16 2018 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Dec 10 2017
Mon Mar  5 16:43:16 2018 library versions: OpenSSL 1.1.0g  2 Nov 2017, LZO 2.08

**Comment by vmotos** [comment]
check if file /opt/4nonimizer/vpn/vpnbook/pass.txt is filled with credentials and or execute vpn-get-pass.sh

**Comment by suryansh55** [comment]
vpn-get-pass.sh where is it located ?

**Comment by vmotos** [comment]
Look into /opt/4nonimizer/vpn/vpnbook/.
There is one vpn-get-pass.sh and vpn-get-ovpns.sh in each VPN provider folder.

**Comment by suryansh55** [comment]
I did all that , I even reinstalled but it seems it gets stuck after this command 
[+] Starting logging process (VPN)...ok.
Nothing happens after this

**Comment by Hackplayers** [comment]
try to execute openvpn name_of_file.ovpn into vpn folder and comment us the result please.

**Comment by vmotos** [comment]
Closed (no answer)

**Comment by charlesashby** [comment]
I had the same problem.. Seems like there's a bug with Tesseract when fetching the vpnbook code.. as of 2019, it has been updated to 6smnvua instead of 6smmvua

**Comment by Heptaknight** [comment]
This problem happens because www.vpnbook.com has changed their password to cmx6z6n.
To solve this problem  enter into this directory "/opt/4nonimizer/vpn/vpnbook/" and edit the "pass.txt" 

Pass to be edited : vpnbook
                              cmx6z6n
