### ISSUE TITLE
There is a problem starting openvpn. Please, check nohup.out for details

### ISSUE THREAD

**Issue by Dylan433447** [Hackplayers/4nonimizer#35]
[+] Starting 4nonimizer to hide your real IP...

..............................

[+] There is a problem starting openvpn. Please, check nohup.out for details

Sun Mar 25 07:57:32 2018 Attempting to establish TCP connection with [AF_INET]142.4.206.228:80 [nonblock]
Sun Mar 25 07:57:33 2018 TCP connection established with [AF_INET]142.4.206.228:80
Sun Mar 25 07:57:33 2018 TCP_CLIENT link local: (not bound)
Sun Mar 25 07:57:33 2018 TCP_CLIENT link remote: [AF_INET]142.4.206.228:80
Sun Mar 25 07:57:33 2018 TLS: Initial packet from [AF_INET]142.4.206.228:80, sid=46efdb87 c84eedb1
Sun Mar 25 07:57:33 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Mar 25 07:57:49 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Mar 25 07:57:49 2018 TLS Error: TLS handshake failed
Sun Mar 25 07:57:49 2018 Fatal TLS error (check_tls_errors_co), restarting
Sun Mar 25 07:57:49 2018 SIGUSR1[soft,tls-error] received, process restarting
Sun Mar 25 07:57:49 2018 Restart pause, 5 second(s)
Sun Mar 25 07:57:51 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Mar 25 07:57:51 2018 TLS Error: TLS handshake failed
Sun Mar 25 07:57:51 2018 SIGUSR1[soft,tls-error] received, process restarting
Sun Mar 25 07:57:51 2018 Restart pause, 5 second(s)
Sun Mar 25 07:57:54 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Sun Mar 25 07:57:54 2018 NOTE: --fast-io is disabled since we are not using UDP
Sun Mar 25 07:57:54 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]198.7.58.147:80
Sun Mar 25 07:57:54 2018 Socket Buffers: R=[87380->87380] S=[16384->16384]
Sun Mar 25 07:57:54 2018 Attempting to establish TCP connection with [AF_INET]198.7.58.147:80 [nonblock]
Sun Mar 25 07:57:55 2018 TCP connection established with [AF_INET]198.7.58.147:80
Sun Mar 25 07:57:55 2018 TCP_CLIENT link local: (not bound)
Sun Mar 25 07:57:55 2018 TCP_CLIENT link remote: [AF_INET]198.7.58.147:80
Sun Mar 25 07:57:55 2018 TLS: Initial packet from [AF_INET]198.7.58.147:80, sid=4e7b20b9 dbf3db00
Sun Mar 25 07:57:56 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Sun Mar 25 07:57:56 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]178.162.193.233:25000
Sun Mar 25 07:57:56 2018 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sun Mar 25 07:57:56 2018 UDP link local: (not bound)
Sun Mar 25 07:57:56 2018 UDP link remote: [AF_INET]178.162.193.233:25000
Sun Mar 25 07:57:56 2018 TLS: Initial packet from [AF_INET]178.162.193.233:25000, sid=d6e06578 cfa9e6db

**Comment by damienrobins** [comment]
Is this Dylan Greene?

**Comment by Hackplayers** [comment]
What's the VPN that you're using?

**Comment by damienrobins** [comment]
Most of the VPN are displaying the similarly error.

**Comment by Hackplayers** [comment]
ok, send us if it pòssible a ovpn file to check the config. (mail: hackplayers at ymail.com)

**Comment by vmotos** [comment]
Closed (no answer).
