### ISSUE TITLE
GeoIP Country Edition: can't resolve hostname

### ISSUE THREAD

**Issue by damienrobins** [Hackplayers/4nonimizer#36]
GeoIP Country Edition: can't resolve hostname

**Comment by damienrobins** [comment]
GeoIP Country Edition: can't resolve hostname
would end up resolving to my ipv6.

**Comment by damienrobins** [comment]
Any idea?

**Comment by Hackplayers** [comment]
Are you using ipv6? In this case, take on mund that 4nonimizer only supports ipv4 at the moment...

**Comment by damienrobins** [comment]
I understand that, I I know this, but it is still leaking dns and not correctly displaying a good out put as it did in the 1.09 beta

**Comment by damienrobins** [comment]
There was many many, different problems in this one.
I have been looking at the script, and I did notice that one of the VPN that calls for a direct link download, is no longer available as well.

**Comment by damienrobins** [comment]
It started out great back in January... Each time it was edit, it had more and more problem.

**Comment by Hackplayers** [comment]
I'm so sorry for that. We plan migrate the tool to python and for that reason we do not make great efforts in the bash version. Anyway send us the logs and details in order to fix the problems.

Regards.

**Comment by damienrobins** [comment]
python would be easier. might I suggest to python 3. We are almost ready for 4th edition anyway.

**Comment by Hackplayers** [comment]
Ok, I'll try 3 version
