### ISSUE TITLE
Can't starrt 4nonimizer

### ISSUE THREAD

**Issue by mpravinkumar** [Hackplayers/4nonimizer#38]
I installed 4nonimizer, but when i try to start it, it showing the following error

           ___                   _           _
          /   |                 (_)         (_)
         / /| |_ __   ___  _ __  _ _ __ ___  _ _______ _ __
        / /_| | '_ \ / _ \| '_ \| | '_  ` _ | |_  / _ \ '__|
        \___  | | | | (_) | | | | | | | | | | |/ /  __/ |
            |_/_| |_|\___/|_| |_|_|_| |_| |_|_/___\___|_|
                                           By Carlos Antonini & Vicente Motos
                                           Version: 1.10

[*] You must install 4nonimizer first!

And when I try to reinstall it

[+] Installing dependences...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u5).
libcurl4-gnutls-dev is already the newest version (7.52.1-5+deb9u5).
tor is already the newest version (0.2.9.14-1).
bzip2 is already the newest version (1.0.6-8.1).
dnscrypt-proxy is already the newest version (1.9.4-1).
dos2unix is already the newest version (7.3.4-3).
easy-rsa is already the newest version (2.2.2-2).
geoip-bin is already the newest version (1.6.9-4).
geoip-database is already the newest version (20170512-1).
nmap is already the newest version (7.40-1).
openvpn is already the newest version (2.4.0-6+deb9u2).
proxychains is already the newest version (3.1-7).
librtmp-dev is already the newest version (2.4+20151223.gitfa8646d.1-1+b1).
unzip is already the newest version (6.0-21).
whois is already the newest version (5.2.17~deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

[+] Installing and linking the init service...

cp: cannot stat '../4nonimizer': No such file or directory
'/usr/bin/4nonimizer' -> '/opt/4nonimizer/4nonimizer'
chmod: cannot access '/opt/4nonimizer/vpn/*/*.sh': No such file or directory
cp: cannot stat '/opt/4nonimizer/4non.service': No such file or directory
chmod: cannot access '/etc/systemd/system/4non.service': No such file or directory
Synchronizing state of tor.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable tor
Failed to enable unit: File 4non.service: No such file or directory

Kindly help me to resolve this issue.

**Comment by Hackplayers** [comment]
try:
git clone https://github.com/Hackplayers/4nonimizer.git
cd 4nonimizer
./4nonimizer install

after check /opt/4nonimizer

**Comment by vmotos** [comment]
Please, feedback

**Comment by mpravinkumar** [comment]
Sorry It is working properly now
Thank you

**Comment by vmotos** [comment]
Perfect!
