### ISSUE TITLE
automated install

### ISSUE THREAD

**Issue by pekeinfo** [Hackplayers/4nonimizer#4]
si en el comando `apt-get install` .... pudierais poner detrás `-y` haría que no estuvieses pendiente de ir dando a `S` y a `Y` para aceptar todo el tiempo.

**Comment by charly837** [comment]
No ponemos el instalador desatendido para que el usuario pueda ver que paquetes se están instalando en que momento, y sea el,  el que decida si instalarlos o no. Y en la vpn no podemos poner el Y cuando le dices que te descargue todos los ovpn porque yo puede querer 1 provider que me descargue todas las ovpn y en otro no, ya que todos las vpn son gratuitas pero en algunas se requiere registro.

**Comment by pekeinfo** [comment]
entiendo :)
