### ISSUE TITLE
Starting logging process (VPN)...dig: couldn't get address for 'resolver1.opendns.com': not found

### ISSUE THREAD

**Issue by ItzL3op4rd** [Hackplayers/4nonimizer#40]
openvpn error

**Comment by vmotos** [comment]
Could you provide us more details, please? Do u have Internet connection when you receive that error?

**Comment by leo860105** [comment]
I have the same issue as well

After installing 4nonimizer, I type ./4nonimizer start, and it gives me the following result

![2018-05-13 18 47 48](https://user-images.githubusercontent.com/17426216/39966478-0061c914-56df-11e8-95d1-c885b7057ddf.jpg)

![2018-05-13 18 48 14](https://user-images.githubusercontent.com/17426216/39966486-123989ce-56df-11e8-861c-cc6da9ae1ed6.jpg)

After all finish, I cannot connect to the internet via browser

**Comment by vmotos** [comment]
We have pushed a new version (1.11). Please, check again and feedback.

**Comment by ItzL3op4rd** [comment]
Same error: [+] There is a problem starting openvpn. Please, check nohup.out for details

**Comment by ItzL3op4rd** [comment]
nohup.out: 
Fri Apr 27 16:24:52 2018 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
Options error: --ca fails with 'ca.ipvanish.com.crt': No such file or directory (errno=2)
Fri Apr 27 16:24:52 2018 WARNING: file 'pass.txt' is group or others accessible
Options error: Please correct these errors.
Use --help for more information.
Sat Jun 16 11:57:32 2018 WARNING: file 'pass.txt' is group or others accessible
Sat Jun 16 11:57:32 2018 OpenVPN 2.4.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar  4 2018
Sat Jun 16 11:57:32 2018 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
Sat Jun 16 11:57:32 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Sat Jun 16 11:57:32 2018 NOTE: --fast-io is disabled since we are not using UDP
Sat Jun 16 11:57:32 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]176.126.237.214:443
Sat Jun 16 11:57:32 2018 Socket Buffers: R=[87380->87380] S=[16384->16384]
Sat Jun 16 11:57:32 2018 Attempting to establish TCP connection with [AF_INET]176.126.237.214:443 [nonblock]
Sat Jun 16 11:57:33 2018 TCP connection established with [AF_INET]176.126.237.214:443
Sat Jun 16 11:57:33 2018 TCP_CLIENT link local: (not bound)
Sat Jun 16 11:57:33 2018 TCP_CLIENT link remote: [AF_INET]176.126.237.214:443
Sat Jun 16 11:57:35 2018 Connection reset, restarting [-1]
Sat Jun 16 11:57:35 2018 SIGUSR1[soft,connection-reset] received, process restarting
Sat Jun 16 11:57:35 2018 Restart pause, 5 second(s)
Sat Jun 16 11:57:40 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Sat Jun 16 11:57:40 2018 NOTE: --fast-io is disabled since we are not using UDP
Sat Jun 16 11:57:41 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]176.126.237.214:443
Sat Jun 16 11:57:41 2018 Socket Buffers: R=[87380->87380] S=[16384->16384]
Sat Jun 16 11:57:41 2018 Attempting to establish TCP connection with [AF_INET]176.126.237.214:443 [nonblock]
Sat Jun 16 11:57:42 2018 TCP connection established with [AF_INET]176.126.237.214:443
Sat Jun 16 11:57:42 2018 TCP_CLIENT link local: (not bound)
Sat Jun 16 11:57:42 2018 TCP_CLIENT link remote: [AF_INET]176.126.237.214:443
Sat Jun 16 11:57:45 2018 Connection reset, restarting [-1]
Sat Jun 16 11:57:45 2018 SIGUSR1[soft,connection-reset] received, process restarting
Sat Jun 16 11:57:45 2018 Restart pause, 5 second(s)
Sat Jun 16 11:57:50 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Sat Jun 16 11:57:50 2018 NOTE: --fast-io is disabled since we are not using UDP
Sat Jun 16 11:57:50 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]176.126.237.214:443
Sat Jun 16 11:57:50 2018 Socket Buffers: R=[87380->87380] S=[16384->16384]
Sat Jun 16 11:57:50 2018 Attempting to establish TCP connection with [AF_INET]176.126.237.214:443 [nonblock]
Sat Jun 16 11:58:55 2018 TCP connection established with [AF_INET]176.126.237.214:443
Sat Jun 16 11:58:55 2018 TCP_CLIENT link local: (not bound)
Sat Jun 16 11:58:55 2018 TCP_CLIENT link remote: [AF_INET]176.126.237.214:443
Sat Jun 16 11:58:57 2018 Connection reset, restarting [-1]
Sat Jun 16 11:58:57 2018 SIGUSR1[soft,connection-reset] received, process restarting
Sat Jun 16 11:58:57 2018 Restart pause, 5 second(s)
Sat Jun 16 11:59:02 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Sat Jun 16 11:59:02 2018 NOTE: --fast-io is disabled since we are not using UDP
Sat Jun 16 11:59:02 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]176.126.237.214:443
Sat Jun 16 11:59:02 2018 Socket Buffers: R=[87380->87380] S=[16384->16384]
Sat Jun 16 11:59:02 2018 Attempting to establish TCP connection with [AF_INET]176.126.237.214:443 [nonblock]
Sat Jun 16 11:59:34 2018 TCP connection established with [AF_INET]176.126.237.214:443
Sat Jun 16 11:59:34 2018 TCP_CLIENT link local: (not bound)
Sat Jun 16 11:59:34 2018 TCP_CLIENT link remote: [AF_INET]176.126.237.214:443
Sat Jun 16 11:59:36 2018 Connection reset, restarting [-1]
Sat Jun 16 11:59:36 2018 SIGUSR1[soft,connection-reset] received, process restarting
Sat Jun 16 11:59:36 2018 Restart pause, 5 second(s)
Sat Jun 16 11:59:41 2018 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Sat Jun 16 11:59:41 2018 NOTE: --fast-io is disabled since we are not using UDP
Sat Jun 16 11:59:41 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]176.126.237.214:443
Sat Jun 16 11:59:41 2018 Socket Buffers: R=[87380->87380] S=[16384->16384]
Sat Jun 16 11:59:41 2018 Attempting to establish TCP connection with [AF_INET]176.126.237.214:443 [nonblock]
Sat Jun 16 12:00:46 2018 TCP connection established with [AF_INET]176.126.237.214:443
Sat Jun 16 12:00:46 2018 TCP_CLIENT link local: (not bound)
Sat Jun 16 12:00:46 2018 TCP_CLIENT link remote: [AF_INET]176.126.237.214:443
Sat Jun 16 12:00:46 2018 TLS: Initial packet from [AF_INET]176.126.237.214:443, sid=5c9d3234 d5cb89cb
Sat Jun 16 12:00:46 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Jun 16 12:00:46 2018 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Sat Jun 16 12:00:46 2018 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Sat Jun 16 12:00:49 2018 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 1024 bit RSA
Sat Jun 16 12:00:49 2018 [vpnbook.com] Peer Connection Initiated with [AF_INET]176.126.237.214:443
Sat Jun 16 12:00:50 2018 SENT CONTROL [vpnbook.com]: 'PUSH_REQUEST' (status=1)
Sat Jun 16 12:00:50 2018 AUTH: Received control message: AUTH_FAILED
Sat Jun 16 12:00:50 2018 SIGTERM[soft,auth-failure] received, process exiting

**Comment by vmotos** [comment]
The last problem is due to auth failed. Please, check if /opt/4nonimizer/vpn/vpnbook/pass.txt or /opt/4nonimizer/vpn/<other provider>/pass.txt is filled with the correct credentials.
