### ISSUE TITLE
sed: can't read /opt/4nonimizer/vpn/proxysh/*.ovpn: No such file or directory

### ISSUE THREAD

**Issue by AmadeusJ** [Hackplayers/4nonimizer#41]
Hi!
First, thank you for '4nonimizer' development !
But I got a problem...
After installation and typing '4nonimizer start'
I got these logs-

==========================

sed: can't read /opt/4nonimizer/vpn/proxysh/ *.ovpn: No such file or directory
ls: cannot access '/opt/4nonimizer/vpn/proxysh/ *.ovpn': No such file or directory
..............................
[+] There is a problem starting openvpn. Please, check nohup.out for details

--pkcs11-pin-cache seconds      : Number of seconds to cache PIN. The default is -1
                                  cache until token is removed.
--pkcs11-id-management          : Acquire identity from management interface.
--pkcs11-id serialized-id 'id'  : Identity to use, get using standalone --show-pkcs11-ids

SSL Library information:
--show-ciphers  : Show cipher algorithms to use with --cipher option.
--show-digests  : Show message digest algorithms to use with --auth option.
--show-engines  : Show hardware crypto accelerator engines (if available).
--show-tls      : Show all TLS ciphers (TLS used only as a control channel).

Generate a random key (only for non-TLS static key encryption mode):
--genkey        : Generate a random key to be used as a shared secret,
                  for use with the --secret option.
--secret file   : Write key to file.

Tun/tap config mode (available with linux 2.4+):
--mktun         : Create a persistent tunnel.
--rmtun         : Remove a persistent tunnel.
--dev tunX|tapX : tun/tap device
--dev-type dt   : Device type.  See tunnel options above for details.
--user user     : User to set privilege to.
--group group   : Group to set privilege to.

PKCS#11 standalone options:
--show-pkcs11-ids provider [cert_private] : Show PKCS#11 available ids.
                                            --verb option can be added *BEFORE* this.

General Standalone Options:
--show-gateway : Show info about default gateway.

====================================

I think that the below logs are seen when I run '# openvpn' in terminal...
I don't know what is the problem...
Thx!!
I'm using kali 2.0

**Comment by AmadeusJ** [comment]
According other issues, they got error at '/opt/4nonimizer/vpn/vpnbook/ *.ovpn' -
So do I change the path '/opt/4nonimizer/vpn/proxysh/ *.ovpn' to '/opt/4nonimizer/vpn/vpnbook/ *.ovpn' in 'start()' function?
In my 'start()' function....
       .......
        sed -i '/auth-user-pass/d' /opt/4nonimizer/vpn/*/*.ovpn
        sed -i "8iauth-user-pass pass.txt" /opt/4nonimizer/vpn/proxysh/*.ovpn
        if [ -z "$SELECTOVPN" ]; then
                SELECTOVPN=$(ls /opt/4nonimizer/vpn/proxysh/*.ovpn | shuf -n 1)
        fi
        current_provider=`cat /opt/4nonimizer/4nonimizer | awk 'NR==67' | awk -F';' '{print $1}' | awk -F'/' '{print $5}'`
        # Avoid DNS leaks
        #sed -i '10s/^/block-outside-dns\n/' /opt/4nonimizer/vpn/vpnbook/*.ovpn
        ......
'sed -i '10s/^/block-outside-dns\n/' /opt/4nonimizer/vpn/vpnbook/*.ovpn' is commented...
Thx-

**Comment by AmadeusJ** [comment]
Yeah_ I was right! After I change the path in 'start()' It works well !
Thx !

**Comment by ghost** [comment]
Guys I need Help With  That start command ! 
Error reading username from Auth authfile: pass.txt
