### ISSUE TITLE
Problem installing 4nonimizer

### ISSUE THREAD

**Issue by am1392** [Hackplayers/4nonimizer#42]
I already clone it and have the directory in my root but when I hit the command:

_4nonimizer install_

this message shows up:

_bash: /usr/bin/4nonimizer: No such file or directory_

Help!

**Comment by mashsajid** [comment]
In your terminal type-
chmod -R 777 4nonimizer
cd 4nonimizer
./4nonimizer install

**Comment by vmotos** [comment]
Problem fixed
