### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by niles1999** [Hackplayers/4nonimizer#44]
cp: cannot stat '../4nonimizer': No such file or directory
'/usr/bin/4nonimizer' -> '/opt/4nonimizer/4nonimizer'
chmod: cannot access '/opt/4nonimizer/vpn/*/*.sh': No such file or directory
cp: cannot stat '/opt/4nonimizer/4non.service': No such file or directory
chmod: cannot access '/etc/systemd/system/4non.service': No such file or directory
Synchronizing state of tor.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable tor
Failed to enable unit: Unit file /etc/systemd/system/tor.service is masked.
Failed to start tor.service: Unit tor.service is masked.
Failed to enable unit: Unit file 4non.service does not exist.

[+] Enter "A" if you want to update all vpn profiles, or wait 1 secs to update only the default one (VPNbook)...
[+] Obtaining Credentials and config files of default vpn (VpnBook)

./4nonimizer: line 231: cd: /opt/4nonimizer/vpn/vpnbook: No such file or directory
sed: can't read /opt/4nonimizer/vpn/*/*.ovpn: No such file or directory
sed: can't read /opt/4nonimizer/vpn/*/*.ovpn: No such file or directory

**Comment by charly837** [comment]
first step: 4nonimizer install with root user
second: 4nonimizer update_vpns
third: 4nonimizer disableboot or enableboot depending on your preferences.
fourth: 4nonimizer start, by default start with vpnbook.

try it and i wait the working fine

**Comment by vmotos** [comment]
Solved
