### ISSUE TITLE
change_ip bug

### ISSUE THREAD

**Issue by Vdevv** [Hackplayers/4nonimizer#45]
when i tried to use change ip command it couldn't find *.ovpn after trying a lot of time different things on the script i found that the SHUF_OVPN variable is wrong so cause it has spaces and thats a problem for a variable :p but its also gets set before the other things that have to been set up already such is the path etc. I simply changed the SHUF_OVPN=$(ls *.ovpn | shuf -n 1 ) TO #SHUF_OVPN=$(ls *.ovpn | shuf -n 1 ) and cd /opt/4nonimizer/vpn/$(cat /opt/4nonimizer/4nonimizer | awk 'NR==67' | awk -F';' '{print $1}' | awk -F'/' '{print $5}')/ ; nohup openvpn $SHUF_OVPN 2> /dev/null &  TO cd /opt/4nonimizer/vpn/$(cat /opt/4nonimizer/4nonimizer | awk 'NR==67' | awk -F';' '{print $1}' | awk -F'/' '{print $5}')/ ; nohup openvpn $(ls *.ovpn | shuf -n 1 ) 2> /dev/null & and now works perfect.

**Comment by vmotos** [comment]
Thanks u so much for the fix. The problem was the order of command 'cd'. I've implemented your suggestion.

Best regards!
