### ISSUE TITLE
Elementary OS not supported.

### ISSUE THREAD

**Issue by igorsonehara** [Hackplayers/4nonimizer#46]
Your distro is not supported. There is any way to install?

**Comment by vmotos** [comment]
We have not installed 4nonimizer in that ditro yet, but if you want you can try to add distro name in the line containing: [ `lsb_release -i | awk '{print $3}'` = Kali ] (substitute 'kali' for the output of lsb_release -i | awk '{print $3}') and, please, send us your feedback.

**Comment by igorsonehara** [comment]
Thanks, it worked.
