### ISSUE TITLE
Error al no encontrar fichero vpn

### ISSUE THREAD

**Issue by pekeinfo** [Hackplayers/4nonimizer#5]
tras hacer un `update_vpns` y luego realizar un `test_availability` esto borra muchas de las vpn que anteriormente descargo. el caso es que cuando realizas el `start` te da un error por que no encuentra los ficheros vpn.

**Comment by vmotos** [comment]
hola gracias por el aviso. He revisado el código y el problema estaba en la salida de las distintas versiones de netcat según la distribución usada. He probado distintas opciones y al final he optado por nmap. Ya está corregido en el branch de desarrollo por si lo quieres probar ya, si no la semana que viene publicaremos una nueva versión con todos lo cambios.
Saludos,
