### ISSUE TITLE
problem with git clone

### ISSUE THREAD

**Issue by jibass** [Hackplayers/4nonimizer#50]
Respositor not found 
Fatal Rexpositor 
Please help me out

**Comment by Vdevv** [comment]
You need to provide more information about it.

**Comment by jibass** [comment]
This are my challenge

**Comment by jibass** [comment]
Here are my challenge

**Comment by Szfaagier** [comment]
sent you an email mate but will write here aswell, git clone this link and should be fine https://github.com/Hackplayers/4nonimizer
