### ISSUE TITLE
REPOSITORY NOT FOUND 

### ISSUE THREAD

**Issue by jibass** [Hackplayers/4nonimizer#52]
I always got issues when about to git clone 4nonimizer
/Destop# git clone https://github.com/Hackerplayers.4nonimizer.git
Cloning into 'Hackerplayers.4nonimizer.....
remote:Not found 
fetal:repository https://github.com/Hackerplayers.4nonimizer.git/' not found 
![img_20181001_192820](https://user-images.githubusercontent.com/43710565/46336641-4b0b8000-c623-11e8-98fc-c9cc9a2a834a.jpg)
![img_20181001_193027](https://user-images.githubusercontent.com/43710565/46336683-742c1080-c623-11e8-815f-41ff9da47bf6.jpg)
PLEASE I NEED SOLUTION TO THIS. UP HERE IS THE IMG OF THE DISPLAY SCREEN

**Comment by Szfaagier** [comment]
use this url to download from git
https://github.com/Hackplayers/4nonimizer

**Comment by Vdevv** [comment]
You placed dot after Hackerplayers so thats why you couldnt download it.
Stick to the official urls avoid copy pasting from other sources.

**Comment by Vdevv** [comment]
Provide more info please.

**Comment by vmotos** [comment]
No more info about intallation problems. Closed.
