### ISSUE TITLE
Package geoip-bin not in Arch Repo

### ISSUE THREAD

**Issue by daebenji** [Hackplayers/4nonimizer#56]
The package is just called geoip in arch. I was able to fix it myself. but for other users you should consider to modify the packages giving to pacman.

change the line 199 of the current build from:
pacman -S --noconfirm geoip-bin geoip-database curl whois openvpn easy-rsa proxychains-ng tor bzip2 nmap dos2unix unzip dnscrypt-proxy sqlite3

to:
pacman -S --noconfirm geoip geoip-database curl whois openvpn easy-rsa proxychains-ng tor bzip2 nmap dos2unix unzip dnscrypt-proxy sqlite3

**Comment by vmotos** [comment]
Fixed. thxs very much!
