### ISSUE TITLE
No IP after start command

### ISSUE THREAD

**Issue by Florensvb** [Hackplayers/4nonimizer#57]
<img width="886" alt="screenshot 2018-12-20 at 11 08 02" src="https://user-images.githubusercontent.com/7792052/50278550-945fb480-0447-11e9-947e-38b92eaa3e88.png">

It looks like openvpn connection is successful but I am not getting a new IP address and I can not access the internet anymore until I stop the 4nonimizer. Any clues?
I am using Kali-Linux inside a VirtualBox with an Alfa Network dongle.

**Comment by vmotos** [comment]
we need more details about the error. Could you paste 'ifconfig' and 'route -n' output command?

**Comment by wesleysiqueira** [comment]
I have the same problem!! 
![print1](https://user-images.githubusercontent.com/15800848/57022270-01a90080-6c05-11e9-8fa7-c0d62d6fd773.png)
![print2](https://user-images.githubusercontent.com/15800848/57022271-02419700-6c05-11e9-9069-395e74e1ffe0.png)
How to solve that?

**Comment by vmotos** [comment]
It seems that the vpn connection has not established correcly because 'tun0' interface does not exist.
Could you provide logs after making vpn cnx?

**Comment by vmotos** [comment]
no answer

**Comment by Phrancoua** [comment]
Hello, 
I definitely have the same porblem there on 4nonimizer. (No need for screenshots because it's the same situation)
What do you mean by provide logs after making vpn cnx ? 
Thanks for helping

**Comment by PauZoffoli** [comment]
Same problem here
```

[+] We're going to confirm if your browsing IP has changed...

[*] Checking IP assigned:

VPN Provider:    vpnbook
IP: 
Country:

 [-] Enter "T" if you want to check also IP through TOR (using proxychains), or wait

...done!

kali@kali:/opt/4nonimizer/vpn/vpnbook$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 10:7b:44:4b:f5:2a brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.94/24 brd 192.168.1.255 scope global dynamic noprefixroute eth0
       valid_lft 24019sec preferred_lft 24019sec
    inet6 fe80::127b:44ff:fe4b:f52a/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

```
