### ISSUE TITLE
.conky problem

### ISSUE THREAD

**Issue by CybernetiX-S3C** [Hackplayers/4nonimizer#59]
Not sure how to initiate this conky rc with another theme i have. Please help me understand.

**Comment by vmotos** [comment]
Open up a terminal window.
Add the necessary repository with the command sudo add-apt-repository ppa:teejee2008/ppa.
Update apt with the command sudo apt-get update.
Install Conky Manager by issuing the command sudo apt-get install conky-manager.
Execute conky and enjoy the widget in your graphical desktop!
