### ISSUE TITLE
Erro en la funcion test_availability

### ISSUE THREAD

**Issue by pekeinfo** [Hackplayers/4nonimizer#6]
Elimina Vpns que estan ok.

![testerror](https://cloud.githubusercontent.com/assets/6626839/19624035/24e4d40c-98e5-11e6-9e85-4d3c4da380ea.PNG)

![testerror1](https://cloud.githubusercontent.com/assets/6626839/19624034/24e22b76-98e5-11e6-9320-7d7743e8da36.PNG)

**Comment by vmotos** [comment]
hola gracias por el aviso. He revisado el código y el problema estaba en la salida de las distintas versiones de netcat según la distribución usada. He probado distintas opciones y al final he optado por nmap. Ya está corregido en el branch de desarrollo por si lo quieres probar ya, si no la semana que viene publicaremos una nueva versión con todos lo cambios. 
Saludos,

**Comment by vmotos** [comment]
He corregido la función sustituyendo el uso de nc por nmap
