### ISSUE TITLE
enable_dns

### ISSUE THREAD

**Issue by c0ldn3s5** [Hackplayers/4nonimizer#61]
When enable_dns I cannot reach webpages

**Comment by JohnModica** [comment]
If you are running dnscrypt in systemctl dbus as a service, you won't need
to enable it using 4non.

**Comment by JohnModica** [comment]
You will want to ensure systemctl status dnscrypt is running first in it's
own. Use systemctl enable dnscrypt to have it start on boot.

**Comment by c0ldn3s5** [comment]
I noticed 4non wasn't worth it in that aspect lol its just being a little buggy. I had to restart dnscrypt right on john
