### ISSUE TITLE
still not work

### ISSUE THREAD

**Issue by Charon1609** [Hackplayers/4nonimizer#62]
could you maybe fix the issue with your script please.. it does not work.. or write down what exactly to do..

**Comment by Charon1609** [comment]
[+] There is a problem starting openvpn. Please, check nohup.out for details

Tue Apr 16 21:22:24 2019 WARNING: file 'pass.txt' is group or others accessible
Tue Apr 16 21:22:24 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Tue Apr 16 21:22:24 2019 library versions: OpenSSL 1.1.1b  26 Feb 2019, LZO 2.10

**Comment by vmotos** [comment]
I suppose you use vpnbook as default provider... please check if the file /opt/4nonimizer/vpn/vpnbook/pass.txt exists and it has the correct permissions. Also check if the credentials are correct visiting: https://www.vpnbook.com/freevpn

**Comment by vmotos** [comment]
closed
