### ISSUE TITLE
There is a problem starting openvpn. Please, check nohup.out for details

### ISSUE THREAD

**Issue by CyberFreddy247** [Hackplayers/4nonimizer#63]
hi guys i'm having a problem on 4nonimizer.
i get this error from starting the 4nonimizer service.
and i did check the pass.txt file, and it shows both username and password for vpnbook
which it's normal.
and i did test it for availability.
and i did try to reinstall and update the tool itself.
and yet nothing works.
here's the error log i have:

[+] There is a problem starting openvpn. Please, check nohup.out for details

Sun Apr 21 09:58:42 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]198.7.62.204:25000
Sun Apr 21 09:58:42 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sun Apr 21 09:58:42 2019 UDP link local: (not bound)
Sun Apr 21 09:58:42 2019 UDP link remote: [AF_INET]198.7.62.204:25000
Sun Apr 21 09:58:43 2019 TLS: Initial packet from [AF_INET]198.7.62.204:25000, sid=6b19ac4a 0c07f4fb
Sun Apr 21 09:58:43 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Apr 21 09:58:43 2019 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Sun Apr 21 09:58:43 2019 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Sun Apr 21 09:58:46 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 1024 bit RSA
Sun Apr 21 09:58:46 2019 [vpnbook.com] Peer Connection Initiated with [AF_INET]198.7.62.204:25000
Sun Apr 21 09:58:47 2019 SENT CONTROL [vpnbook.com]: 'PUSH_REQUEST' (status=1)
Sun Apr 21 09:58:47 2019 AUTH: Received control message: AUTH_FAILED
Sun Apr 21 09:58:47 2019 SIGTERM[soft,auth-failure] received, process exiting
Sun Apr 21 10:13:24 2019 WARNING: file 'pass.txt' is group or others accessible
Sun Apr 21 10:13:24 2019 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2018
Sun Apr 21 10:13:24 2019 library versions: OpenSSL 1.1.0g  2 Nov 2017, LZO 2.08
Sun Apr 21 10:13:24 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Sun Apr 21 10:13:24 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]51.68.180.4:25000
Sun Apr 21 10:13:24 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sun Apr 21 10:13:24 2019 UDP link local: (not bound)
Sun Apr 21 10:13:24 2019 UDP link remote: [AF_INET]51.68.180.4:25000
Sun Apr 21 10:13:24 2019 TLS: Initial packet from [AF_INET]51.68.180.4:25000, sid=7d8d8391 87588089
Sun Apr 21 10:13:24 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Apr 21 10:13:24 2019 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Sun Apr 21 10:13:24 2019 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Sun Apr 21 10:13:27 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 1024 bit RSA
Sun Apr 21 10:13:27 2019 [vpnbook.com] Peer Connection Initiated with [AF_INET]51.68.180.4:25000
Sun Apr 21 10:13:28 2019 SENT CONTROL [vpnbook.com]: 'PUSH_REQUEST' (status=1)
Sun Apr 21 10:13:28 2019 AUTH: Received control message: AUTH_FAILED
Sun Apr 21 10:13:28 2019 SIGTERM[soft,auth-failure] received, process exiting

please can you help me with this problem?

**Comment by vmotos** [comment]
Please, check if the file /opt/4nonimizer/vpn/vpnbook/pass.txt contains the correct credentials visiting: https://www.vpnbook.com/freevpn

**Comment by vmotos** [comment]
no answer
