### ISSUE TITLE
OpenVpn Problem Here

### ISSUE THREAD

**Issue by ZentGho** [Hackplayers/4nonimizer#64]
Hello!

I just installed 4nonimizer, and after start it shows error:

[+] There is a problem starting openvpn. Please, check nohup.out for details

Sun Apr 21 22:18:27 2019 WARNING: file 'pass.txt' is group or others accessible
Sun Apr 21 22:18:27 2019 OpenVPN 2.4.7 i686-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Sun Apr 21 22:18:27 2019 library versions: OpenSSL 1.1.1b  26 Feb 2019, LZO 2.10
Sun Apr 21 22:19:57 2019 ERROR: Failed retrieving username or password
Sun Apr 21 22:19:57 2019 Exiting due to fatal error
Sun Apr 21 22:20:50 2019 WARNING: file 'pass.txt' is group or others accessible
Sun Apr 21 22:20:50 2019 OpenVPN 2.4.7 i686-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Sun Apr 21 22:20:50 2019 library versions: OpenSSL 1.1.1b  26 Feb 2019, LZO 2.10
Sun Apr 21 22:22:22 2019 WARNING: file 'pass.txt' is group or others accessible
Sun Apr 21 22:22:22 2019 OpenVPN 2.4.7 i686-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Sun Apr 21 22:22:22 2019 library versions: OpenSSL 1.1.1b  26 Feb 2019, LZO 2.10

Can you please tell me how to solve it?
Thank you in advance!

**Comment by vmotos** [comment]
I suppose you use vpnbook as default provider... please check if the file /opt/4nonimizer/vpn/vpnbook/pass.txt exists. Also check if the credentials are correct visiting: https://www.vpnbook.com/freevpn

**Comment by vmotos** [comment]
no answer

**Comment by nlusr864** [comment]
@vmotos pass.txt exists & how do i check the credintials ? i mean  couldn't find it on the site you provided

**Comment by nlusr864** [comment]
There is a problem starting openvpn. Please, check nohup.out for details
WARNING: file 'pass.txt' is group or others accessible
 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Error reading username from Auth authfile: pass.txt
 Exiting due to fatal error . 


this is what i get when i start 4nonimizer
