### ISSUE TITLE
Problem starting openvpn

### ISSUE THREAD

**Issue by aronschiphof** [Hackplayers/4nonimizer#66]
+] Your current IP is **.***.**.***...

[+] Starting 4nonimizer to hide your real IP...

sed: can't read /opt/4nonimizer/vpn/vpnbook/*.ovpn: No such file or directory
ls: cannot access '/opt/4nonimizer/vpn/vpnbook/*.ovpn': No such file or directory

What should I do?

**Comment by vmotos** [comment]
Could you check if the path exists in your system? Have you installed the tool correctly?

**Comment by vmotos** [comment]
No answer.
