### ISSUE TITLE
No existe el archivo o el directorio

### ISSUE THREAD

**Issue by maravento** [Hackplayers/4nonimizer#7]
cp: no se puede efectuar `stat' sobre '../4nonimizer': No existe el archivo o el directorio
'/usr/bin/4nonimizer' -> '/opt/4nonimizer/4nonimizer'
cp: no se puede efectuar `stat' sobre '/opt/4nonimizer/4non.service': No existe el archivo o el directorio
chmod: no se puede acceder a '/opt/4nonimizer/vpn/*/*.sh': No existe el archivo o el directorio
Synchronizing state of tor.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable tor
insserv: warning: current start runlevel(s) (empty) of script `tor' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `tor' overrides LSB defaults (0 1 6).

4nonimizer/4nonimizer: línea 206: cd: /opt/4nonimizer/vpn/vpnbook: No existe el archivo o el directorio
sed: no se puede leer /opt/4nonimizer/vpn/*/*.ovpn: No existe el archivo o el directorio
sed: no se puede leer /opt/4nonimizer/vpn/*/*.ovpn: No existe el archivo o el directorio

Ubuntu 16.04.2 xenial x64

Instalacion:
git clone https://github.com/Hackplayers/4nonimizer.git
sudo 4nonimizer/4nonimizer install

Update:
sudo 4nonimizer/4nonimizer start

[+] Starting 4nonimizer to hide your real IP...

sed: no se puede leer /opt/4nonimizer/vpn/*/*.ovpn: No existe el archivo o el directorio
sed: no se puede leer /opt/4nonimizer/vpn/*/*.ovpn: No existe el archivo o el directorio
./4nonimizer/4nonimizer: línea 73: cd: /opt/4nonimizer/vpn/vpnbook/: No existe el archivo o el directorio
ls: no se puede acceder a '*.ovpn': No existe el archivo o el directorio
..............................[3;J

[+] There is a problem starting openvpn. Please, check nohup.out for details

cat: /opt/4nonimizer/4nonimizer: No existe el archivo o el directorio
tail: no se puede abrir '/opt/4nonimizer/vpn//nohup.out' para lectura: No existe el archivo o el directorio

**Comment by vmotos** [comment]
hola!
parece que el problema puede ser por dos razones. Por favor, haz lo siguientes:
- desinstala, haz un git clone y vuelve a instalar
- comprueba que tu distro soporta systemd

Saludos,

**Comment by maravento** [comment]
ok
